SELECT TOP (1000)
         [ProductKey] 
      ,[OrderDateKey]
      ,[DueDateKey]
      ,[ShipDateKey]
      ,[CustomerKey] 
      --,[PromotionKey]
      --,[CurrencyKey] 
      --,[SalesTerritoryKey] 
      ,[SalesOrderNumber] 
      --,[SalesOrderLineNumber]
      --,[RevisionNumber]
      --,[OrderQuantity]
      ,[UnitPrice] 
      --,[ExtendedAmount]
      --,[UnitPriceDiscountPct]
      --,[DiscountAmount]
      --,[ProductStandardCost]
      ,[TotalProductCost] 
      ,[SalesAmount] 
      ,[TaxAmt] 
     -- ,[Freight] as freight
      --,[CarrierTrackingNumber]
      --,[CustomerPONumber]
     -- ,[OrderDate] 
     -- ,[DueDate]
     -- ,[ShipDate] 
	  FROM [dbo].[FactInternetSales] 
	  where LEFT (OrderDateKey , 4) >= year(Getdate())-2
	  order by OrderDateKey asc